"""Example: Generate a professional PDF report with custom theming.

Run:
    python examples/generate_report.py
"""

from docforge import DocumentGenerator, Theme


def main():
    # Custom theme — swap colors, branding, etc.
    theme = Theme(
        name="hln",
        brand_name="Hidden Leaf Networks",
        footer_text="Generated by Hidden Leaf Networks",
        footer_url="hiddenleafnetworks.com",
        primary="#14B8A6",
        secondary="#F97316",
    )

    gen = DocumentGenerator(theme=theme)

    # Generate from markdown content
    content = """
## Executive Summary

This report demonstrates DocForge's document generation capabilities.
Professional formatting, configurable theming, and markdown parsing
are all handled automatically.

## Key Features

- **Configurable themes** — Colors, fonts, branding, page layout
- **Markdown parsing** — Headings, lists, bold, italic, code
- **Professional cover pages** — With metadata and branding
- **Multiple output formats** — PDF, Word, and multi-format export

## Technical Details

### Architecture

DocForge separates theming from content generation. A `Theme` object
defines visual properties, while the `DocumentGenerator` handles
the layout and rendering logic.

### Supported Content Formats

1. Plain markdown strings
2. Structured section dictionaries
3. AI-generated content with `generated_content` key

## Conclusion

DocForge makes it easy to generate professional documents
programmatically with full control over branding and styling.
"""

    metadata = {
        "author": "DocForge Team",
        "organization": "Hidden Leaf Networks",
        "document_type": "report",
        "location": "Remote",
    }

    path = gen.create_pdf("/tmp/docforge_example.pdf", "DocForge Example Report", content, metadata)
    print(f"PDF generated: {path}")

    # Simple PDF (no cover page)
    simple_path = gen.create_simple_pdf(
        "/tmp/docforge_simple.pdf",
        "Quick Note",
        "Just a simple document with **bold** and *italic* text.\n\n- Item one\n- Item two",
        metadata={"author": "Jane", "organization": "Acme"},
    )
    print(f"Simple PDF generated: {simple_path}")


if __name__ == "__main__":
    main()
