"""Multi-format chat/conversation export — PDF, TXT, CSV, XLSX.

Standalone export service with no database or framework dependencies.
"""

from __future__ import annotations

import csv
import os
from dataclasses import dataclass
from datetime import datetime
from typing import Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer


@dataclass
class ChatMessage:
    """Standardized chat message for export."""

    role: str
    content: str
    created_at: Optional[datetime] = None
    tokens_used: Optional[int] = None
    model: Optional[str] = None


@dataclass
class ExportMetadata:
    """Metadata for export headers/footers."""

    title: str
    user_name: Optional[str] = None
    user_email: Optional[str] = None
    organization: Optional[str] = None
    project_title: Optional[str] = None
    session_id: Optional[str] = None
    export_type: str = "chat"
    brand_name: str = "DocForge"


class ChatExportService:
    """Export chat conversations to TXT, PDF, CSV, and XLSX formats."""

    SUPPORTED_FORMATS = ["txt", "pdf", "csv", "xlsx"]

    @staticmethod
    def generate_filename(metadata: ExportMetadata, fmt: str) -> str:
        """Generate a unique filename for the export."""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        prefix = f"chat_{metadata.export_type}"
        if metadata.session_id:
            prefix = f"session_{metadata.session_id}"
        return f"{prefix}_{timestamp}.{fmt}"

    @classmethod
    def export_to_txt(
        cls,
        messages: list[ChatMessage],
        metadata: ExportMetadata,
        export_dir: str,
    ) -> str:
        """Export chat messages to plain text."""
        os.makedirs(export_dir, exist_ok=True)
        filename = cls.generate_filename(metadata, "txt")
        filepath = os.path.join(export_dir, filename)

        with open(filepath, "w", encoding="utf-8") as f:
            f.write("=" * 60 + "\n")
            f.write(f"CHAT EXPORT: {metadata.title}\n")
            f.write("=" * 60 + "\n\n")

            if metadata.user_name:
                f.write(f"User: {metadata.user_name}\n")
            if metadata.organization:
                f.write(f"Organization: {metadata.organization}\n")
            if metadata.project_title:
                f.write(f"Project: {metadata.project_title}\n")

            f.write(f"Export Date: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}\n")
            f.write(f"Total Messages: {len(messages)}\n")
            f.write("\n" + "-" * 60 + "\n\n")

            for msg in messages:
                role_label = "USER" if msg.role == "user" else "ASSISTANT"
                ts = f"[{msg.created_at.strftime('%Y-%m-%d %H:%M')}]" if msg.created_at else "[No timestamp]"
                f.write(f"{ts} {role_label}:\n{msg.content}\n\n")

            f.write("-" * 60 + "\n")
            f.write(f"Generated by {metadata.brand_name}\n")

        return filepath

    @classmethod
    def export_to_pdf(
        cls,
        messages: list[ChatMessage],
        metadata: ExportMetadata,
        export_dir: str,
    ) -> str:
        """Export chat messages to PDF."""
        os.makedirs(export_dir, exist_ok=True)
        filename = cls.generate_filename(metadata, "pdf")
        filepath = os.path.join(export_dir, filename)

        doc = SimpleDocTemplate(filepath, pagesize=letter)
        base_styles = getSampleStyleSheet()
        story: list = []

        title_style = ParagraphStyle(
            "ExportTitle", parent=base_styles["Heading1"],
            fontSize=20, textColor=colors.HexColor("#1a1a1a"),
            spaceAfter=20, alignment=1,
        )
        user_style = ParagraphStyle(
            "UserMsg", parent=base_styles["Normal"],
            fontSize=10, textColor=colors.HexColor("#1a1a1a"),
            backColor=colors.HexColor("#e8f4f8"),
            borderPadding=8, spaceBefore=8, spaceAfter=8, leftIndent=20,
        )
        assistant_style = ParagraphStyle(
            "AssistantMsg", parent=base_styles["Normal"],
            fontSize=10, textColor=colors.HexColor("#1a1a1a"),
            backColor=colors.HexColor("#f0f0f0"),
            borderPadding=8, spaceBefore=8, spaceAfter=8, rightIndent=20,
        )
        role_style = ParagraphStyle(
            "RoleLabel", parent=base_styles["Normal"],
            fontSize=8, textColor=colors.HexColor("#666666"), spaceBefore=12,
        )

        story.append(Paragraph(f"Chat Export: {metadata.title}", title_style))
        story.append(Spacer(1, 0.1 * inch))

        meta_lines = []
        if metadata.user_name:
            meta_lines.append(f"<b>User:</b> {metadata.user_name}")
        if metadata.organization:
            meta_lines.append(f"<b>Organization:</b> {metadata.organization}")
        if metadata.project_title:
            meta_lines.append(f"<b>Project:</b> {metadata.project_title}")
        meta_lines.append(f"<b>Export Date:</b> {datetime.now().strftime('%B %d, %Y')}")
        meta_lines.append(f"<b>Total Messages:</b> {len(messages)}")

        for line in meta_lines:
            story.append(Paragraph(line, base_styles["Normal"]))
        story.append(Spacer(1, 0.3 * inch))

        for msg in messages:
            role_label = "You" if msg.role == "user" else "AI Assistant"
            ts = f" - {msg.created_at.strftime('%b %d, %Y %I:%M %p')}" if msg.created_at else ""
            story.append(Paragraph(f"<b>{role_label}</b>{ts}", role_style))

            safe = msg.content.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            safe = safe.replace("\n", "<br/>")
            story.append(Paragraph(safe, user_style if msg.role == "user" else assistant_style))

        story.append(Spacer(1, 0.5 * inch))
        footer_style = ParagraphStyle(
            "ExportFooter", parent=base_styles["Normal"],
            fontSize=8, textColor=colors.HexColor("#999999"), alignment=1,
        )
        story.append(Paragraph(f"Generated by {metadata.brand_name}", footer_style))
        doc.build(story)
        return filepath

    @classmethod
    def export_to_csv(
        cls,
        messages: list[ChatMessage],
        metadata: ExportMetadata,
        export_dir: str,
    ) -> str:
        """Export chat messages to CSV."""
        os.makedirs(export_dir, exist_ok=True)
        filename = cls.generate_filename(metadata, "csv")
        filepath = os.path.join(export_dir, filename)

        with open(filepath, "w", newline="", encoding="utf-8") as f:
            writer = csv.writer(f)
            writer.writerow(["Message #", "Timestamp", "Role", "Content", "Tokens Used"])
            for i, msg in enumerate(messages, 1):
                ts = msg.created_at.strftime("%Y-%m-%d %H:%M:%S") if msg.created_at else ""
                writer.writerow([i, ts, msg.role.capitalize(), msg.content, msg.tokens_used or ""])

        return filepath

    @classmethod
    def export_to_xlsx(
        cls,
        messages: list[ChatMessage],
        metadata: ExportMetadata,
        export_dir: str,
    ) -> str:
        """Export chat messages to Excel with styling.

        Requires the `excel` extra: `pip install docforge[excel]`
        """
        try:
            from openpyxl import Workbook
            from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
        except ImportError:
            raise ImportError(
                "openpyxl is required for Excel export. "
                "Install with: pip install docforge[excel]"
            )

        os.makedirs(export_dir, exist_ok=True)
        filename = cls.generate_filename(metadata, "xlsx")
        filepath = os.path.join(export_dir, filename)

        wb = Workbook()
        summary_ws = wb.active
        summary_ws.title = "Summary"

        header_font = Font(bold=True, size=14)
        label_font = Font(bold=True)
        header_fill = PatternFill(start_color="4472C4", end_color="4472C4", fill_type="solid")
        header_font_white = Font(bold=True, color="FFFFFF")
        user_fill = PatternFill(start_color="E2EFDA", end_color="E2EFDA", fill_type="solid")
        assistant_fill = PatternFill(start_color="DDEBF7", end_color="DDEBF7", fill_type="solid")
        thin_border = Border(
            left=Side(style="thin"), right=Side(style="thin"),
            top=Side(style="thin"), bottom=Side(style="thin"),
        )

        summary_ws["A1"] = "Chat Export Summary"
        summary_ws["A1"].font = header_font
        summary_ws.merge_cells("A1:B1")

        summary_data = [
            ("Title", metadata.title),
            ("User", metadata.user_name or "N/A"),
            ("Organization", metadata.organization or "N/A"),
            ("Project", metadata.project_title or "N/A"),
            ("Export Date", datetime.now().strftime("%B %d, %Y %I:%M %p")),
            ("Total Messages", len(messages)),
            ("User Messages", sum(1 for m in messages if m.role == "user")),
            ("Assistant Messages", sum(1 for m in messages if m.role == "assistant")),
        ]

        for i, (label, value) in enumerate(summary_data, 3):
            summary_ws[f"A{i}"] = label
            summary_ws[f"A{i}"].font = label_font
            summary_ws[f"B{i}"] = value

        summary_ws.column_dimensions["A"].width = 20
        summary_ws.column_dimensions["B"].width = 40

        messages_ws = wb.create_sheet("Messages")
        headers = ["Message #", "Timestamp", "Role", "Content", "Tokens Used"]
        for col, header in enumerate(headers, 1):
            cell = messages_ws.cell(row=1, column=col, value=header)
            cell.font = header_font_white
            cell.fill = header_fill
            cell.alignment = Alignment(horizontal="center", vertical="center")
            cell.border = thin_border

        for i, msg in enumerate(messages, 2):
            ts = msg.created_at.strftime("%Y-%m-%d %H:%M:%S") if msg.created_at else ""
            row_data = [i - 1, ts, msg.role.capitalize(), msg.content, msg.tokens_used or ""]
            fill = user_fill if msg.role == "user" else assistant_fill
            for col, value in enumerate(row_data, 1):
                cell = messages_ws.cell(row=i, column=col, value=value)
                cell.fill = fill
                cell.border = thin_border
                cell.alignment = Alignment(wrap_text=True, vertical="top") if col == 4 else Alignment(vertical="top")

        messages_ws.column_dimensions["A"].width = 10
        messages_ws.column_dimensions["B"].width = 20
        messages_ws.column_dimensions["C"].width = 12
        messages_ws.column_dimensions["D"].width = 80
        messages_ws.column_dimensions["E"].width = 12
        messages_ws.freeze_panes = "A2"

        wb.save(filepath)
        return filepath

    @classmethod
    def export(
        cls,
        messages: list[ChatMessage],
        metadata: ExportMetadata,
        fmt: str,
        export_dir: str,
    ) -> str:
        """Export chat messages to the specified format.

        Args:
            messages: List of ChatMessage objects.
            metadata: Export metadata.
            fmt: Format string (txt, pdf, csv, xlsx).
            export_dir: Directory to write the export file.

        Returns:
            Filepath to the generated export file.

        Raises:
            ValueError: If format is not supported.
        """
        fmt = fmt.lower()
        if fmt not in cls.SUPPORTED_FORMATS:
            raise ValueError(f"Unsupported format: {fmt}. Supported: {cls.SUPPORTED_FORMATS}")

        exporters = {
            "txt": cls.export_to_txt,
            "pdf": cls.export_to_pdf,
            "csv": cls.export_to_csv,
            "xlsx": cls.export_to_xlsx,
        }
        return exporters[fmt](messages, metadata, export_dir)
